# Spring Application Configuration
spring.application.name=doctype-backend
server.port=8080

# Database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/doctype
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JWT Configuration
app.jwt.secret=8fK29xLmPq7R2vN5aBcD9eFgHjKlMnOpQrStUvWxYz123456
app.jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.doctype=DEBUG

# Error Handling
server.error.include-message=always
server.error.include-stacktrace=on_param
server.error.include-exception=false
